### ISSUE TITLE
Exception Handling - Acessando indice 

### ISSUE THREAD

**Issue by isdrchagas** [devs-javagirl/java-trainning#30]
Crie um programa em Java que declare um array de inteiros com tamanho 8. Em seguida, peça ao usuário para digitar qual índice deseja acessar, printe o valor e caso o índice não exista, certifique-se de tratar a exceção lançada.

**Comment by mariacavalc** [comment]
Olá, tenho interesse em resolver essa issue 😊

**Comment by isdrchagas** [comment]
@mariacavalc atribuimos a issue a você :)

**Comment by mariacavalc** [comment]
PR aberto
