### ISSUE TITLE
Exception Handling - Arquivo não encontrado

### ISSUE THREAD

**Issue by isdrchagas** [devs-javagirl/java-trainning#31]
Crie um programa que tente abrir um arquivo de texto (por exemplo, "arquivo.txt") usando a classe `FileInputStream`. Certifique-se de tratar a exceção lançada caso o arquivo não exista.

**Comment by CamilaBodack** [comment]
Olá @isdrchagas, posso trabalhar nessa ?

**Comment by isdrchagas** [comment]
pode sim, atribui essa para você tbm @CamilaBodack
