### ISSUE TITLE
Exception Handling - NPE

### ISSUE THREAD

**Issue by isdrchagas** [devs-javagirl/java-trainning#32]
Crie uma classe `Produto` com um atributo **descricao**. Em seguida, crie um objeto `Produto` e tente acessar o atributo **descricao** sem atribuir um valor a ele, trate a exceção lançada.

**Comment by BrunaCelestino** [comment]
Ola. Poderia trabalhar nessa issue?

**Comment by gleiceellen** [comment]
@BrunaCelestino a issue é sua! Bom trabalho!
