### ISSUE TITLE
Exception Handling - Customizando exceções 

### ISSUE THREAD

**Issue by isdrchagas** [devs-javagirl/java-trainning#33]
Crie uma exceção personalizada chamada `IdadeInvalidaException`. Em seguida, crie uma classe `Pessoa` com um atributo **idade** e um método para checar a idade. Caso a idade seja menor que 0 ou maior que 150, lance a exceção personalizada que foi criada.

**Comment by CamilaBodack** [comment]
Olá @isdrchagas, posso trabalhar nessa issue ?
