### ISSUE TITLE
Exception Handling -  Leitura e processamento de arquivo

### ISSUE THREAD

**Issue by isdrchagas** [devs-javagirl/java-trainning#34]
Crie um programa que leia dados de um arquivo e processe esses dados. Garanta que o arquivo seja fechado corretamente, independentemente das exceções que ocorrerem durante o processamento.

**Comment by JessikaFujimura** [comment]
Oie, gostaria de trabalhar nesta issue.

Fico no aguardo,
Obrigada!

**Comment by isdrchagas** [comment]
bem-vinda @JessikaFujimura, atribui ela a você :)
