### ISSUE TITLE
Exception Handling - Múltiplas exceções

### ISSUE THREAD

**Issue by isdrchagas** [devs-javagirl/java-trainning#36]
Crie um programa que seja capaz de lidar com diferentes tipos de exceções.

**Comment by gawadeatul** [comment]
Você pode atribuir esse problema para mim, gostaria de contribuir.

**Comment by isdrchagas** [comment]
Olá @gawadeatul, somos uma comunidade tecnológica focada na união de mulheres envolvidas com Java, sejam elas desenvolvedoras experientes ou iniciantes. Nosso propósito é promover a inclusão e o aprendizado, proporcionando um ambiente acolhedor para mulheres que codam em Java ou têm interesse no assunto. Dito isso, agradecemos seu interesse mas damos prioridade para mulheres resolverem as issues, tá bem?

**Comment by isdrchagas** [comment]
seja bem-vinda @jessicamosouza, atribui ela a você :D
